# Nome do contexto Camel
camel.context.name = meu-camel-contexto

# Faz a aplicação parar após o processamento de 1 mensagem
camel.main.durationMaxMessages = -1

# Alternativa: Rodar por 10 segundos e parar
# camel.main.durationMaxSeconds = 10

# Habilitar log no console
quarkus.log.console.enable=true

# Definir o nível mínimo de log do console para INFO ou DEBUG
quarkus.log.console.level=INFO

# Alternativa: Definir log específico para suas rotas (ex: seu pacote)
quarkus.log.category."com.br.flavioreboucassantos.camelmicroservice.routes.a".level=INFO