quarkus.http.host=0.0.0.0
quarkus.http.port=80

whatsapp_webhook.my_verify_token=
whatsapp_send.phone_number_id=
whatsapp_send.whatsapp_token=

kafka.bootstrap.servers=localhost:9092

camel.component.kafka.brokers=${kafka.bootstrap.servers}