# quarkus.http
quarkus.http.port=8080
quarkus.http.root-path=

# Configure Hibernate to automatically manage the schema
quarkus.hibernate-orm.database.generation = drop-and-create

# quarkus.datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/db_book_trip
quarkus.datasource.jdbc.max-size=16

# Habilitar o componente Saga
camel.saga.enabled = true

# URL do Coordenador LRA (ex: Narayana)
camel.lra.coordinator-url = http://localhost:8080